### PR TITLE
zetuprc: Add Python 3.7

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
Python 3.7 passes all tests except the version, c.f. spec and logs at https://build.opensuse.org/package/show/devel:languages:python/python-zetup

**Comment by dotlambda** [comment]
To make the tests work, a pytest version <4 has to be used.

**Comment by jayvdb** [comment]
Thanks.  Fixed

**Comment by userzimmermann** [comment]
@jayvdb @dotlambda Oops :D Only saw this PR right now! I meanwhile added `3.7` myself (and dropped `3.4`)

Anyway... Since you were first to do so, and I don't want this contribution to just vanish into the void, I'll nevertheless take it over ;)

**Review by userzimmermann — APPROVED** [review]

**Pull request merged**
